
runtime: python312
     
  # or your specific Python version
instance_class: F2  # Adjust based on your needs

env: flexible  # or 'flex' if using the flexible environment
api_version: 1
threadsafe: true

handlers:
- url: /
  script: home.app

- url: /index\.html
  script: home.app

- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: not_found.app

# handlers:
#   - url: /static
#     static_dir: static/
    
#   - url: /.*
#     script: auto

# Optional settings
env_variables:
  APPENGINE_URL: https://django1deploy.uc.r.appspot.com
  DJANGO_SETTINGS_MODULE: "root.settings"
  SECRET_KEY: env("SECRET_KEY")  # Make sure to keep this secret!

entrypoint: gunicorn -b :$PORT --timeout=600 main:app